name: Clang Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          for file in $(find . -name "*.c"); do
            echo "Checking $file"
            clang-format --style=file --dry-run --Werror "$file"
          done
